/**
 * MORROW persistent schema (SQLite via Drizzle).
 *
 * Conventions:
 * - Primary keys are prefixed ULID strings generated by @morrow/shared (never display names).
 * - Timestamps are epoch milliseconds in INTEGER columns.
 * - Enumerations are TEXT validated by the Zod domain schemas on read and write.
 * - Structured values are JSON in TEXT columns.
 * - Secrets are never stored here; only references into the OS credential store.
 *
 * Changing this file requires generating a migration: `pnpm db:generate`.
 */
import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text, uniqueIndex, primaryKey } from "drizzle-orm/sqlite-core";

// ── Projects & tasks ──────────────────────────────────────────────────────

export const projects = sqliteTable("projects", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description"),
  rootPath: text("root_path"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
  archivedAt: integer("archived_at"),
});

export const tasks = sqliteTable(
  "tasks",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
    title: text("title").notNull(),
    objective: text("objective").notNull(),
    status: text("status").notNull(),
    statusReason: text("status_reason", { mode: "json" }).$type<{ code: string; message: string }>(),
    pausedFrom: text("paused_from"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
    startedAt: integer("started_at"),
    endedAt: integer("ended_at"),
    version: integer("version").notNull().default(0),
    result: text("result", { mode: "json" }),
  },
  (t) => [index("tasks_status_idx").on(t.status), index("tasks_project_idx").on(t.projectId)],
);

export const taskSteps = sqliteTable(
  "task_steps",
  {
    id: text("id").primaryKey(),
    taskId: text("task_id")
      .notNull()
      .references(() => tasks.id, { onDelete: "cascade" }),
    planId: text("plan_id"),
    ordinal: integer("ordinal").notNull(),
    title: text("title").notNull(),
    description: text("description"),
    status: text("status").notNull(),
    expectedToolIds: text("expected_tool_ids", { mode: "json" }).$type<string[]>().notNull().default([]),
    outcome: text("outcome"),
    toolExecutionId: text("tool_execution_id"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => [index("task_steps_task_idx").on(t.taskId, t.ordinal)],
);

/**
 * Plan versions of a task. task_steps.plan_id refers to the version that created
 * the step. Exactly one version per task is ACTIVE; earlier versions are kept.
 */
export const plans = sqliteTable(
  "plans",
  {
    id: text("id").primaryKey(),
    taskId: text("task_id")
      .notNull()
      .references(() => tasks.id, { onDelete: "cascade" }),
    version: integer("version").notNull(),
    previousPlanId: text("previous_plan_id"),
    status: text("status").notNull(),
    summary: text("summary").notNull(),
    successCriteria: text("success_criteria", { mode: "json" }).$type<string[]>().notNull(),
    /** Grounded criteria (JSON array); NULL for plans created before grounded verification. */
    criteria: text("criteria", { mode: "json" }).$type<unknown[]>(),
    keptStepIds: text("kept_step_ids", { mode: "json" }).$type<string[]>().notNull().default([]),
    reason: text("reason"),
    triggerObservationIds: text("trigger_observation_ids", { mode: "json" }).$type<string[]>().notNull().default([]),
    modelId: text("model_id"),
    createdAt: integer("created_at").notNull(),
    supersededAt: integer("superseded_at"),
  },
  (t) => [uniqueIndex("plans_task_version_idx").on(t.taskId, t.version)],
);

// ── Events & observations ─────────────────────────────────────────────────

/** Append-only. Rows are never updated or deleted by application code. */
export const events = sqliteTable(
  "events",
  {
    sequence: integer("sequence").primaryKey({ autoIncrement: true }),
    id: text("id").notNull(),
    type: text("type").notNull(),
    schemaVersion: integer("schema_version").notNull(),
    occurredAt: integer("occurred_at").notNull(),
    actorKind: text("actor_kind").notNull(),
    actorId: text("actor_id"),
    taskId: text("task_id"),
    projectId: text("project_id"),
    correlationId: text("correlation_id"),
    causationId: text("causation_id"),
    payload: text("payload", { mode: "json" }).notNull(),
  },
  (t) => [
    uniqueIndex("events_id_idx").on(t.id),
    index("events_task_idx").on(t.taskId, t.sequence),
    index("events_type_idx").on(t.type),
    index("events_correlation_idx").on(t.correlationId),
  ],
);

export const observations = sqliteTable(
  "observations",
  {
    id: text("id").primaryKey(),
    taskId: text("task_id"),
    stepId: text("step_id"),
    source: text("source", { mode: "json" }).notNull(),
    summary: text("summary").notNull(),
    data: text("data", { mode: "json" }),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [index("observations_task_idx").on(t.taskId)],
);

// ── Memory ────────────────────────────────────────────────────────────────

export const memories = sqliteTable(
  "memories",
  {
    id: text("id").primaryKey(),
    type: text("type").notNull(),
    status: text("status").notNull(),
    content: text("content").notNull(),
    origin: text("origin").notNull(),
    confidence: real("confidence").notNull(),
    projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
    taskId: text("task_id"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
    lastVerifiedAt: integer("last_verified_at"),
    expiresAt: integer("expires_at"),
    revision: integer("revision").notNull(),
  },
  (t) => [
    index("memories_scope_idx").on(t.projectId, t.status, t.type),
    index("memories_task_idx").on(t.taskId),
  ],
);

export const memorySources = sqliteTable(
  "memory_sources",
  {
    id: text("id").primaryKey(),
    memoryId: text("memory_id")
      .notNull()
      .references(() => memories.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    ref: text("ref"),
    excerpt: text("excerpt"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [index("memory_sources_memory_idx").on(t.memoryId)],
);

export const memoryRelations = sqliteTable(
  "memory_relations",
  {
    id: text("id").primaryKey(),
    fromMemoryId: text("from_memory_id")
      .notNull()
      .references(() => memories.id, { onDelete: "cascade" }),
    toMemoryId: text("to_memory_id")
      .notNull()
      .references(() => memories.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [index("memory_relations_from_idx").on(t.fromMemoryId), index("memory_relations_to_idx").on(t.toMemoryId)],
);

export const memoryRevisions = sqliteTable(
  "memory_revisions",
  {
    id: text("id").primaryKey(),
    memoryId: text("memory_id")
      .notNull()
      .references(() => memories.id, { onDelete: "cascade" }),
    revision: integer("revision").notNull(),
    content: text("content").notNull(),
    status: text("status").notNull(),
    confidence: real("confidence").notNull(),
    reason: text("reason").notNull(),
    actor: text("actor").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [uniqueIndex("memory_revisions_memory_rev_idx").on(t.memoryId, t.revision)],
);

// ── Tools & permissions ───────────────────────────────────────────────────

/** Snapshot of tools registered by the runtime, refreshed at startup. */
export const tools = sqliteTable("tools", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description").notNull(),
  version: text("version").notNull(),
  category: text("category").notNull(),
  riskLevel: text("risk_level").notNull(),
  capabilities: text("capabilities", { mode: "json" }).$type<string[]>().notNull(),
  inputJsonSchema: text("input_json_schema", { mode: "json" }).notNull(),
  outputJsonSchema: text("output_json_schema", { mode: "json" }).notNull(),
  availability: text("availability", { mode: "json" }).notNull(),
  registeredAt: integer("registered_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

/** Permission requirements a tool declares (capability + risk). Not grants. */
export const toolPermissions = sqliteTable(
  "tool_permissions",
  {
    toolId: text("tool_id")
      .notNull()
      .references(() => tools.id, { onDelete: "cascade" }),
    capability: text("capability").notNull(),
    riskLevel: text("risk_level").notNull(),
    rationale: text("rationale").notNull(),
  },
  (t) => [primaryKey({ columns: [t.toolId, t.capability] })],
);

export const toolExecutions = sqliteTable(
  "tool_executions",
  {
    id: text("id").primaryKey(),
    toolId: text("tool_id").notNull(),
    toolVersion: text("tool_version").notNull(),
    taskId: text("task_id"),
    stepId: text("step_id"),
    status: text("status").notNull(),
    purpose: text("purpose"),
    input: text("input", { mode: "json" }),
    output: text("output", { mode: "json" }),
    error: text("error", { mode: "json" }),
    requestedAt: integer("requested_at").notNull(),
    startedAt: integer("started_at"),
    finishedAt: integer("finished_at"),
  },
  (t) => [index("tool_executions_task_idx").on(t.taskId), index("tool_executions_status_idx").on(t.status)],
);

/** Permission grants: standing user decisions about capabilities. */
export const permissions = sqliteTable(
  "permissions",
  {
    id: text("id").primaryKey(),
    capability: text("capability").notNull(),
    effect: text("effect").notNull(),
    scope: text("scope").notNull(),
    scopeRef: text("scope_ref"),
    constraints: text("constraints", { mode: "json" }),
    origin: text("origin").notNull(),
    createdAt: integer("created_at").notNull(),
    expiresAt: integer("expires_at"),
    revokedAt: integer("revoked_at"),
    consumedAt: integer("consumed_at"),
  },
  (t) => [index("permissions_capability_idx").on(t.capability)],
);

export const permissionRequests = sqliteTable(
  "permission_requests",
  {
    id: text("id").primaryKey(),
    executionId: text("execution_id").notNull(),
    toolId: text("tool_id").notNull(),
    capability: text("capability").notNull(),
    riskLevel: text("risk_level").notNull(),
    taskId: text("task_id"),
    projectId: text("project_id"),
    resource: text("resource"),
    reason: text("reason").notNull(),
    status: text("status").notNull(),
    createdAt: integer("created_at").notNull(),
    resolvedAt: integer("resolved_at"),
    resolvedScope: text("resolved_scope"),
  },
  (t) => [index("permission_requests_status_idx").on(t.status)],
);

// ── Models ────────────────────────────────────────────────────────────────

export const modelProviders = sqliteTable("model_providers", {
  id: text("id").primaryKey(),
  adapter: text("adapter").notNull(),
  locality: text("locality").notNull(),
  displayName: text("display_name").notNull(),
  endpoint: text("endpoint"),
  secretRef: text("secret_ref"),
  enabled: integer("enabled", { mode: "boolean" }).notNull(),
  state: text("state").notNull(),
  stateMessage: text("state_message"),
  checkedAt: integer("checked_at"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const models = sqliteTable(
  "models",
  {
    id: text("id").primaryKey(),
    providerId: text("provider_id")
      .notNull()
      .references(() => modelProviders.id, { onDelete: "cascade" }),
    providerModelId: text("provider_model_id").notNull(),
    displayName: text("display_name").notNull(),
    locality: text("locality").notNull(),
    capabilities: text("capabilities", { mode: "json" }).notNull(),
    contextWindow: integer("context_window"),
    available: integer("available", { mode: "boolean" }).notNull(),
    discoveredAt: integer("discovered_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => [uniqueIndex("models_provider_model_idx").on(t.providerId, t.providerModelId)],
);

export const modelUsage = sqliteTable(
  "model_usage",
  {
    id: text("id").primaryKey(),
    modelId: text("model_id").notNull(),
    taskId: text("task_id"),
    purpose: text("purpose").notNull(),
    inputTokens: integer("input_tokens"),
    outputTokens: integer("output_tokens"),
    latencyMs: integer("latency_ms").notNull(),
    succeeded: integer("succeeded", { mode: "boolean" }).notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [index("model_usage_model_idx").on(t.modelId), index("model_usage_task_idx").on(t.taskId)],
);

// ── Artifacts & research ──────────────────────────────────────────────────

export const artifacts = sqliteTable(
  "artifacts",
  {
    id: text("id").primaryKey(),
    projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
    taskId: text("task_id"),
    kind: text("kind").notNull(),
    title: text("title").notNull(),
    uri: text("uri").notNull(),
    mimeType: text("mime_type"),
    contentHash: text("content_hash"),
    sizeBytes: integer("size_bytes"),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [index("artifacts_project_idx").on(t.projectId), index("artifacts_task_idx").on(t.taskId)],
);

export const artifactRelations = sqliteTable("artifact_relations", {
  id: text("id").primaryKey(),
  fromArtifactId: text("from_artifact_id")
    .notNull()
    .references(() => artifacts.id, { onDelete: "cascade" }),
  toArtifactId: text("to_artifact_id")
    .notNull()
    .references(() => artifacts.id, { onDelete: "cascade" }),
  kind: text("kind").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const researchSources = sqliteTable("research_sources", {
  id: text("id").primaryKey(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "set null" }),
  taskId: text("task_id"),
  kind: text("kind").notNull(),
  uri: text("uri").notNull(),
  title: text("title"),
  retrievedAt: integer("retrieved_at").notNull(),
  contentHash: text("content_hash"),
  reliability: real("reliability"),
});

export const researchEvidence = sqliteTable(
  "research_evidence",
  {
    id: text("id").primaryKey(),
    sourceId: text("source_id")
      .notNull()
      .references(() => researchSources.id, { onDelete: "cascade" }),
    claim: text("claim").notNull(),
    excerpt: text("excerpt").notNull(),
    locator: text("locator"),
    confidence: real("confidence").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [index("research_evidence_source_idx").on(t.sourceId)],
);

// ── Integrations ──────────────────────────────────────────────────────────

export const connectors = sqliteTable("connectors", {
  id: text("id").primaryKey(),
  kind: text("kind").notNull(),
  displayName: text("display_name").notNull(),
  status: text("status").notNull(),
  secretRef: text("secret_ref"),
  scopes: text("scopes", { mode: "json" }).$type<string[]>().notNull(),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

export const mcpServers = sqliteTable("mcp_servers", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  transport: text("transport", { mode: "json" }).notNull(),
  enabled: integer("enabled", { mode: "boolean" }).notNull(),
  trust: text("trust").notNull(),
  status: text("status").notNull(),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

// ── Settings ──────────────────────────────────────────────────────────────

export const settings = sqliteTable("settings", {
  key: text("key").primaryKey(),
  value: text("value", { mode: "json" }).notNull(),
  updatedAt: integer("updated_at")
    .notNull()
    .default(sql`(unixepoch() * 1000)`),
});
